### ISSUE TITLE
"update mirror" button is disabled if can't visit google

### ISSUE THREAD

**Issue by yejianfengblue** [arcolinux/arcolinux-welcome-app#4]
China user here ^_^. This method tests google and disables button "update arch mirrors".

https://github.com/arcolinux/arcolinux-welcome-app/blob/5c53e845cdc60e20f76344a0a7371dcb8d033fcb/usr/share/arcolinux-welcome-app/arcolinux-welcome-app.py#L961-L980

I can edit it manually to bypass.
How about change the test address to `www.archlinux.org` or `www.bing.com` which is less possible to be blocked? So other new users can install arco more easily.
https://github.com/arcolinux/arcolinux-welcome-app/blob/5c53e845cdc60e20f76344a0a7371dcb8d033fcb/usr/share/arcolinux-welcome-app/arcolinux-welcome-app.py#L29

![Screenshot_20240901_214454](https://github.com/user-attachments/assets/61de158b-c23c-43ac-b9fb-93a37935b976)

**Comment by arcolinuxz** [comment]
just open a terminal

and type

mirror
or
mirrors
or
...
many other mirror variants
